### PR TITLE
bin: prints help message when meets unknown arguments

### LINKED ISSUE #1549: Should print help message when meet unknown command line arguments
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
latest

2. What operating system and processor architecture are you using?
macOS/Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

``
./tidb-latest-linux-amd64/bin/tikv-server --some-unkown-option
thread 'main' panicked at 'opts parse failed: UnrecognizedOption("some-unkown-option")', ../src/libcore/result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
``

4. What did you expect to see?

TiKV should print help message.

### PR DESCRIPTION
**Pull request by overvenus**
PTAL  @siddontang @BusyJay @andelf 

Close #1549

### CODE REVIEW

File: src/bin/tikv-server.rs [hunk 1]
```diff
@@ -711,9 +711,12 @@ fn main() {
                 "attributes about this server",
                 "zone=example-zone,disk=example-disk");
 
-    let matches = opts.parse(&args[1..]).expect("opts parse failed");
+    let matches = opts.parse(&args[1..]).unwrap_or_else(|e| {
+        print_usage(&program, &opts);
+        exit_with_err(format!("opts parse failed, {:?}", e));
```
Comment (siddontang) [inline src/bin/tikv-server.rs]: seem we should output the error first, then help message and then exit.

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM
