### PR TITLE
*: use another connection for snapshot.

### LINKED ISSUE #442: Use another connection to send snapshot
If snapshot is too large, it will block pending heartbeat, which may cause a new round of election. In the worst case, it will cause TiKV to stop responding for a long time, which may crash TiDB.

### PR DESCRIPTION
**Pull request by siddontang**
Fix #442 

Now origin test can covers this, I will add more tests later. 

@ngaut @BusyJay @disksing

### CODE REVIEW

File: src/server/conn.rs [hunk 1]
```diff
@@ -160,18 +166,33 @@ impl Conn {
             self.res.pop_front();
         }
 
-        // no data for writing, remove writable.
+        // no data for writing, remove writable
         self.interest.remove(EventSet::writable());
-        self.reregister(event_loop)
+        try!(self.reregister(event_loop));
+
+        self.on_write_complete(true);
```
Comment (BusyJay) [inline src/server/conn.rs]: How can we ensure that the callback is called when the corresponding message rather than another one is written?

File: src/server/conn.rs [hunk 2]
```diff
@@ -160,18 +166,33 @@ impl Conn {
...
     pub fn append_write_buf<T, S>(&mut self,
                                   event_loop: &mut EventLoop<Server<T, S>>,
-                                  msg: ConnData)
+                                  msg: ConnData,
+                                  cb: Option<OnWriteComplete>)
                                   -> Result<()>
         where T: RaftStoreRouter,
               S: StoreAddrResolver
     {
+        self.write_complete = cb;
```
Comment (BusyJay) [inline src/server/conn.rs]: What if `self.write_complete` is some?

File: src/server/conn.rs (hunk 1 above)
Comment (siddontang) [inline src/server/conn.rs]: no guarantee here. this callback just means being called when writing all data ok. 

Refer tornado 3.2 https://github.com/tornadoweb/tornado/blob/branch3.2/tornado/iostream.py

File: src/server/conn.rs (hunk 2 above)
Comment (siddontang) [inline src/server/conn.rs]: overwrite directly.

File: src/server/conn.rs [hunk 3]
```diff
@@ -185,9 +215,11 @@ impl Conn {
             // if registered, we can only remove this flag when
             // writing all data in writable function.
             self.interest.insert(EventSet::writable());
-            return self.reregister(event_loop);
+            try!(self.reregister(event_loop));
         }
 
+        self.on_write_complete = cb;
```
Comment (BusyJay) [inline src/server/conn.rs]: Maybe we should figure out a more reliable way later.

**Comment by BusyJay** [comment]
LGTM

File: src/server/conn.rs (hunk 3 above)
Comment (siddontang) [inline src/server/conn.rs]: Maybe no need now, you can see many other libs like libev libevent also overwrite old callback.
And you can send data, then re-send other in write complete callback again, this is a universal way.

**Comment by siddontang** [comment]
PTAL @ngaut @disksing

File: src/server/conn.rs [hunk 4]
```diff
@@ -160,14 +180,24 @@ impl Conn {
             self.res.pop_front();
         }
 
-        // no data for writing, remove writable.
+        // no data for writing, remove writable
         self.interest.remove(EventSet::writable());
-        self.reregister(event_loop)
+        try!(self.reregister(event_loop));
+
```
Comment (ngaut) [inline src/server/conn.rs]: Remove empty line.

File: src/server/resolve.rs [hunk 5]
```diff
@@ -48,6 +48,8 @@ pub struct Runner<T: PdClient> {
 
 impl<T: PdClient> Runner<T> {
     fn resolve(&self, store_id: u64) -> Result<SocketAddr> {
+        // TODO: cache store address for some time so that we can use it
```
Comment (ngaut) [inline src/server/resolve.rs]: Yes, we should cache it.

Comment (siddontang) [inline src/server/resolve.rs]: Another PR, not this now.

Comment (siddontang) [inline src/server/resolve.rs]: I will fire an issue later.

**Comment by ngaut** [comment]
LGTM
