### PR TITLE
Check pd list format

### LINKED ISSUE #1274: check validation for pd list format.
One user passes ":2379,127.0.0.2:2379,127.0.0.3:2379" to tikv, although tikv can work correctly, it   is still better to panic because of the wrong pd list format.

### PR DESCRIPTION
**Pull request by overvenus**
`validate_addrs` validates a list of addresses. Addresses are formed like "Host:Port".
More details about **Host** and **Port** can be found in RFC3986 section 3.2.2 and 3.2.3.

Close #1274 

PTAL @siddontang @BusyJay

### CODE REVIEW

File: src/util/config.rs [hunk 1]
```diff
@@ -113,10 +120,67 @@ pub fn parse_readable_int(size: &str) -> Result<i64, ParseConfigError> {
...
 
+/// `validate_addrs` validates a list of addresses. Addresses are formed like "Host:Port".
+/// More details about **Host** and **Port** can be found in RFC3986 section 3.2.2 and 3.2.3.
+pub fn validate_addrs(addrs: &[&str]) -> Result<(), ConfigError> {
+    fn new_err(addr: &str) -> ConfigError {
+        ConfigError::PDList(format!("invalid addr: {}", addr))
+    }
+
+    for addr in addrs {
+        if let (Err(_), Err(_)) = (SocketAddrV4::from_str(addr), SocketAddrV6::from_str(addr)) {
```
Comment (siddontang) [inline src/util/config.rs]: using from_str is not enough?

Comment (siddontang) [inline src/util/config.rs]:
```
if v4::from_str().ok() 
   return

if v6::from_str().ok()
  return

check host:port 
```

Comment (siddontang) [inline src/util/config.rs]: abstract a single function to check the addr.

File: src/util/config.rs [hunk 2]
```diff
@@ -113,8 +120,60 @@ pub fn parse_readable_int(size: &str) -> Result<i64, ParseConfigError> {
...
+            let port: u16 = try!(parts[1]
+                .parse()
+                .map_err(|_| new_err(addr)));
+            // Port = 0 is invalid.
+            if port == 0 {
+                return Err(new_err(addr));
+            }
+
+            // Check Host.
+            for c in parts[0].chars() {
```
Comment (siddontang) [inline src/util/config.rs]: I think it is still a little complex here. We can reference Go https://golang.org/pkg/net/#SplitHostPort, https://golang.org/src/net/ipsock.go

For host:port, it only check whether it can be split into two parts with ":".

Comment (siddontang) [inline src/util/config.rs]: If we pass an invalid host, or an unreachable host, we can check in following `connect`, not here.

File: src/util/config.rs [hunk 3]
```diff
@@ -113,10 +121,48 @@ pub fn parse_readable_int(size: &str) -> Result<i64, ParseConfigError> {
...
+            continue;
+        }
+
+        let parts: Vec<&str> = addr.split(':')
+            .filter(|s| !s.is_empty()) // "Host:" or ":Port" are invalid.
+            .collect();
+
+        // ["Host", "Port"]
+        if parts.len() != 2 {
+            return Err(ConfigError::PDList(format!("invalid addr: {}", addr)));
```
Comment (siddontang) [inline src/util/config.rs]: the function is for checking common addr, not only for PD.

Comment (siddontang) [inline src/util/config.rs]: I think you can define Address error instead of PDList.

**Comment by siddontang** [comment]
LGTM
PTAL @BusyJay @huachaohuang
