### PR TITLE
store: change box err to stale epoch error

### LINKED ISSUE #2593: test_node_base_split_region_right_derive failed
hi, `test_node_base_split_region_right_derive` failed with the following details on jenkins:
http://45.249.247.133:8080/blue/organizations/jenkins/tikv_ghpr_unit_test/detail/tikv_ghpr_unit_test/150/pipeline/20/
```
thread 'raftstore-5::test_node_base_split_region_right_derive' panicked at 'failed to split: message: "[region 1000] 1001 epoch changed conf_ver: 1 version: 3 != conf_ver: 1 version: 2, need re-check later"', tests/raftstore/cluster.rs:768:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:362
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:276
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:48
   9: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
  10: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
  11: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  12: <integrations::raftstore::cluster::Cluster<T>>::must_split::{{closure}}
test raftstore_cases::test_split_region::test_node_delay_split_region ... ok
             at tests/raftstore/cluster.rs:768
  13: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:143
  14: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:682
  15: <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once
             at /checkout/src/liballoc/boxed.rs:702
  16: <tikv::raftstore::store::store::Store<T, C>>::on_prepare_split_region::{{closure}}
             at ./src/raftstore/store/store.rs:1858
  17: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  18: <tikv::raftstore::store::store::Store<T, C>>::on_prepare_split_region
             at ./src/raftstore/store/store.rs:1858
  19: <tikv::raftstore::store::store::Store<T, C> as mio::handler::Handler>::notify
             at ./src/raftstore/store/store.rs:2487
  20: <mio::event_loop::EventLoop<H>>::notify
             at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:350
  21: <mio::event_loop::EventLoop<H>>::run_once
             at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:299
  22: <mio::event_loop::EventLoop<H>>::run
             at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:247
  23: <tikv::raftstore::store::store::Store<T, C>>::run
             at ./src/raftstore/store/store.rs:545
  24: <tikv::server::node::Node<C>>::start_store::{{closure}}
             at ./src/server/node.rs:362
thread 'raftstore_cases::test_split_region::test_node_base_split_region_right_derive' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for Duration { secs: 5, nanos: 0 }")', /checkout/src/libcore/result.rs:860:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:362
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:276
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:48
   9: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
  10: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
  11: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  12: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
  13: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
  14: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:31
  15: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  16: <integrations::raftstore::cluster::Cluster<T>>::query_leader
             at tests/raftstore/cluster.rs:281
  17: <integrations::raftstore::cluster::Cluster<T>>::leader_of_region
             at tests/raftstore/cluster.rs:319
  18: <integrations::raftstore::cluster::Cluster<T>>::call_command_on_leader
             at tests/raftstore/cluster.rs:233
  19: <integrations::raftstore::cluster::Cluster<T>>::request
             at tests/raftstore/cluster.rs:516
  20: <integrations::raftstore::cluster::Cluster<T>>::must_put_cf
             at tests/raftstore/cluster.rs:591
  21: <integrations::raftstore::cluster::Cluster<T>>::must_put
             at tests/raftstore/cluster.rs:587
  22: integrations::raftstore_cases::test_split_region::test_base_split_region
             at tests/raftstore_cases/test_split_region.rs:80
  23: integrations::raftstore_cases::test_split_region::test_node_base_split_region_right_derive
             at tests/raftstore_cases/test_split_region.rs:118
  24: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  25: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
thread 'raftstore_cases::test_split_region::test_node_base_split_region_right_derive' panicked at 'called `Result::unwrap()` on an `Err` value: Other(Closed)', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0:     0x7fadafbb11a3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hc32b3550469bd7ec
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fadafbad754 - std::sys_common::backtrace::_print::h18ec9a3165b0d7ba
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x7fadafbb4943 - std::panicking::default_hook::{{closure}}::hcead061326bfc66a
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:     0x7fadafbb46a2 - std::panicking::default_hook::h6a8c02fe69584b6b
                               at /checkout/src/libstd/panicking.rs:396
   4:     0x7fadae042789 - tikv::util::panic_hook::track_hook::{{closure}}::he4b7619911f2a73c
                               at src/util/panic_hook.rs:61
   5:     0x7fadade09e8d - <std::thread::local::LocalKey<T>>::try_with::hc1d10ce1c9c28d97
                               at /checkout/src/libstd/thread/local.rs:362
   6:     0x7fadade094ec - <std::thread::local::LocalKey<T>>::with::h1e04e77ff771795b
                               at /checkout/src/libstd/thread/local.rs:276
   7:     0x7fadae463cee - tikv::util::panic_hook::track_hook::hbfeb49144b456099
                               at src/util/panic_hook.rs:55
   8:     0x7fadae2fc978 - core::ops::function::Fn::call::hc7797a6ed162dcc2
                               at /checkout/src/libcore/ops/function.rs:48
   9:     0x7fadafbb4e86 - std::panicking::rust_panic_with_hook::h536d0075488cfad3
                               at /checkout/src/libstd/panicking.rs:611
  10:     0x7fadafbb4d14 - std::panicking::begin_panic::h59163d4c7e23a4b5
                               at /checkout/src/libstd/panicking.rs:571
  11:     0x7fadafbb4c19 - std::panicking::begin_panic_fmt::h226cbf2ee66e31a5
                               at /checkout/src/libstd/panicking.rs:521
  12:     0x7fadafbb4baa - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:497
  13:     0x7fadafbe32a0 - core::panicking::panic_fmt::h232071f163afd174
                               at /checkout/src/libcore/panicking.rs:71
  14:     0x7fadad5168b4 - core::result::unwrap_failed::hca3280c65de924d0
                               at /checkout/src/libcore/macros.rs:31
  15:     0x7fadad2511f6 - <core::result::Result<T, E>>::unwrap::h0d26b4f0faa7f9bc
                               at /checkout/src/libcore/result.rs:738
  16:     0x7fadadb56d38 - <integrations::raftstore::node::NodeCluster as integrations::raftstore::cluster::Simulator>::stop_node::hccbee8dca237036b
                               at tests/raftstore/node.rs:238
  17:     0x7fadadb354ca - <integrations::raftstore::cluster::Cluster<T>>::stop_node::he97c80c659cf2759
                               at tests/raftstore/cluster.rs:177
  18:     0x7fadadb4109c - <integrations::raftstore::cluster::Cluster<T>>::shutdown::hc1fdba3c9317d84c
                               at tests/raftstore/cluster.rs:467
  19:     0x7fadadb5361c - <integrations::raftstore::cluster::Cluster<T> as core::ops::drop::Drop>::drop::h37fe55f293f0ad82
                               at tests/raftstore/cluster.rs:856
  20:     0x7fadad473514 - core::ptr::drop_in_place::h7426ff1341cfba16
                               at /checkout/src/libcore/ptr.rs:61
  21:     0x7fadadba60db - integrations::raftstore_cases::test_split_region::test_node_base_split_region_right_derive::h5437bbbff2d766ec
                               at tests/raftstore_cases/test_split_region.rs:119
  22:     0x7fadadd24f81 - <F as test::FnBox<T>>::call_box::h5e82055b2788b0b0
                               at /checkout/src/libtest/lib.rs:1477
                               at /checkout/src/libcore/ops/function.rs:143
                               at /checkout/src/libtest/lib.rs:138
  23:     0x7fadafbbbf9c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  24:     0x7fadadd158fc - std::sys_common::backtrace::__rust_begin_short_backtrace::hed881682075c7641
                               at /checkout/src/libstd/panicking.rs:458
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libtest/lib.rs:1416
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  25:     0x7fadadd166c2 - std::panicking::try::do_call::hfb55048cb24e8c46
                               at /checkout/src/libstd/thread/mod.rs:364
                               at /checkout/src/libstd/panic.rs:296
                               at /checkout/src/libstd/panicking.rs:479
  26:     0x7fadafbbbf9c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  27:     0x7fadadd1e8c2 - <F as alloc::boxed::FnBox<A>>::call_box::h38e755be7f3e288a
                               at /checkout/src/libstd/panicking.rs:458
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/thread/mod.rs:363
                               at /checkout/src/liballoc/boxed.rs:682
  28:     0x7fadafbb3aab - std::sys::imp::thread::Thread::new::thread_start::h0aeebbbbd5e5d9cd
                               at /checkout/src/liballoc/boxed.rs:692
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  29:     0x7fadac4a0e24 - start_thread
  30:     0x7fadabfb834c - __clone
  31:                0x0 - <unknown>
thread panicked while panicking. aborting.
error: An unknown error occurred
```

@overvenus @zhangjinpeng1987 PTAL

### PR DESCRIPTION
**Pull request by overvenus**
Fix #2593 and #2487 

Tests will retry when it meets stale epoch error.

### CODE REVIEW

File: src/raftstore/store/store.rs [hunk 1]
```diff
@@ -1918,19 +1918,23 @@ impl<T: Transport, C: PdClient> Store<T, C> {
...
                 peer.tag,
                 region.get_region_epoch(),
                 epoch
             );
-            return Err(box_err!(
-                "{} epoch changed {:?} != {:?}, need re-check later",
-                peer.tag,
-                region.get_region_epoch(),
-                epoch
+            return Err(Error::StaleEpoch(
```
Comment (siddontang) [inline src/raftstore/store/store.rs]: why can return StaleEpoch fix the problem?

Comment (overvenus) [reply src/raftstore/store/store.rs]: https://github.com/pingcap/tikv/blob/d780a5f9ba18cdb2a7063172079ff9bfe27a06d4/tests/raftstore/cluster.rs#L762-L769

The line 768 panics if the respones has a box error, however it will retry, if the error is the stale epoch.

**Comment by siddontang** [comment]
LGTM

PTAL @BusyJay

**Comment by ngaut** [comment]
Nice catch.
