### PR TITLE
tikv-ctl: add `bad-regions` subcommand.

### LINKED ISSUE #2612: tikv-ctl check all regions which can't launch
If a node failed, it maybe can't startup success because some regions could have broken raft states or partial snapshots. So tikv-ctl should have a subcommand to check all those regions. And then we can recover them, or just remove the store.

### PR DESCRIPTION
**Pull request by hicqu**
close #2612 

Now the command can check all regions which have corrupted `last index`, `commited index` or `applied index`. But it can't handle bad snapshot until now.

### CODE REVIEW

**Comment by siddontang** [comment]
can you give me some examples, like damaging some region metas and using our tool?

**Comment by hicqu** [comment]
I have add some test cases to show how the command check bad regions. PTAL thanks.

File: src/bin/tikv-ctl.rs [hunk 1]
```diff
@@ -490,6 +492,10 @@ impl DebugExecutor for DebugClient {
     fn set_region_tombstone(&self, _: u64, _: Region) {
         unimplemented!();
     }
+
+    fn print_bad_regions(&self) {
+        panic!("only avaliable for local mode");
```
Comment (overvenus) [inline src/bin/tikv-ctl.rs]: How about `unimplemented!`?

**Comment by siddontang** [comment]
Great work

**Comment by hicqu** [comment]
@overvenus PTAL again, thanks.
